// Shared product category taxonomy. Mirrored (not imported — separate app, no shared package)
// in backend/src/constants/categories.js. Keep the two lists in sync when editing.
export const CATEGORY_GROUPS: Record<string, string[]> = {
  "Electronics & Appliances": [
    "Mobile Phones & Accessories",
    "Laptops & Computers",
    "Computer Accessories",
    "Cameras & Photography",
    "TVs & Home Theater",
    "Audio & Headphones",
    "Gaming & Consoles",
    "Wearable Tech",
    "Kitchen Appliances",
    "Home Appliances",
    "Power & Batteries",
    "Networking Equipment",
  ],
  "Fashion & Apparel": [
    "Men's Clothing",
    "Women's Clothing",
    "Kids' Clothing",
    "Traditional & Habesha Wear",
    "Shoes & Footwear",
    "Bags & Luggage",
    "Watches",
    "Jewelry & Accessories",
    "Eyewear",
  ],
  "Beauty & Personal Care": [
    "Skincare",
    "Haircare",
    "Makeup & Cosmetics",
    "Fragrances",
    "Personal Hygiene",
    "Men's Grooming",
    "Health Supplements",
  ],
  "Home & Living": [
    "Furniture",
    "Home Decor",
    "Bedding & Linens",
    "Kitchenware & Dining",
    "Storage & Organization",
    "Lighting",
    "Garden & Outdoor",
    "Cleaning Supplies",
  ],
  "Food & Beverage": [
    "Coffee & Tea",
    "Spices & Seasonings",
    "Snacks & Confectionery",
    "Bakery",
    "Beverages",
    "Organic & Health Foods",
    "Meal Prep & Catering",
  ],
  "Baby, Kids & Toys": [
    "Baby Gear",
    "Diapers & Feeding",
    "Toys & Games",
    "Kids Furniture",
    "School Supplies",
  ],
  "Sports & Outdoors": [
    "Fitness Equipment",
    "Sportswear",
    "Outdoor & Camping Gear",
    "Bicycles & Accessories",
    "Team Sports Equipment",
  ],
  "Books, Media & Hobbies": [
    "Books & Stationery",
    "Musical Instruments",
    "Arts & Crafts",
    "Collectibles",
    "Board Games & Puzzles",
  ],
  Automotive: [
    "Car Parts & Accessories",
    "Motorcycle Parts & Accessories",
    "Car Care & Detailing",
    "Tires & Wheels",
  ],
  "Agriculture & Livestock": [
    "Seeds & Seedlings",
    "Farm Equipment",
    "Livestock & Poultry",
    "Fertilizers & Pesticides",
    "Animal Feed",
  ],
  "Health & Wellness Products": [
    "Medical Supplies",
    "Fitness & Nutrition Products",
    "Mobility Aids",
    "First Aid",
  ],
  "Office & Industrial": [
    "Office Supplies",
    "Office Furniture",
    "Industrial Equipment",
    "Safety Equipment",
    "Packaging Supplies",
  ],
  "Real Estate": [
    "Houses for Sale",
    "Houses for Rent",
    "Apartments for Rent",
    "Commercial Property",
    "Land for Sale",
  ],
  // --- Services ---
  "Home Services": [
    "Cleaning Services",
    "Plumbing",
    "Electrical Repair",
    "Painting & Decorating",
    "Carpentry",
    "Appliance Repair",
    "Pest Control",
    "Moving & Relocation",
    "Gardening & Landscaping",
    "Interior Design",
  ],
  "Professional Services": [
    "Accounting & Bookkeeping",
    "Legal Services",
    "Business Consulting",
    "Marketing & Advertising",
    "HR & Recruitment",
    "Translation Services",
    "Notary Services",
  ],
  "Digital & Tech Services": [
    "Web Development",
    "App Development",
    "Graphic Design",
    "IT Support",
    "Social Media Management",
    "Video Editing",
    "Data Entry",
    "SEO Services",
  ],
  "Education & Training": [
    "Tutoring",
    "Language Lessons",
    "Music Lessons",
    "Test Prep",
    "Professional Certification Training",
    "Vocational Training",
  ],
  "Health & Beauty Services": [
    "Spa & Massage",
    "Hair Salon",
    "Barbershop",
    "Nail Care",
    "Personal Training",
    "Nutrition Coaching",
    "Therapy & Counseling",
  ],
  "Events & Entertainment": [
    "Event Planning",
    "Photography Services",
    "Videography Services",
    "Catering Services",
    "DJ & Live Music",
    "Venue Rental",
    "Decoration Services",
  ],
  "Transport & Logistics": [
    "Ride Services",
    "Courier & Delivery",
    "Freight & Trucking",
    "Car Rental",
    "Vehicle Repair Services",
  ],
  "Construction & Real Estate Services": [
    "Construction & Contracting",
    "Architecture & Engineering",
    "Real Estate Agency",
    "Property Management",
    "Renovation Services",
  ],
  Other: ["Miscellaneous Goods", "Miscellaneous Services"],
};

export const CATEGORIES = Object.values(CATEGORY_GROUPS).flat();
